### PR TITLE
Add info on importing Cambridge data

### PR DESCRIPTION
**Pull request by davidread**

### CODE REVIEW

**Comment by davidread** [comment]
This now ready for review/merge @andreagrandi

**Comment by davidread** [comment]
Output when I run this:
```
4,008 Ignore - not vacant e.g. ['Cambridge City Council', 'http://opendatacommunities.org/id/district-council/cambridge', '1/10/2016', '200004202581', '0000347004002A', '01/04/1990', '12th Cambs Scout Group', '40a, Gilbert Road, Cambridge, CB4 3PE', '5600', 'LC3', '', '0', '5600', '', '       SBRE', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'SBRE', '1/4/2016', '', '', '']
19 Error - no LR data for uprn e.g. ['Cambridge City Council', 'http://opendatacommunities.org/id/district-council/cambridge', '1/10/2016', '010090969147', '00004870000110', '27/08/2016', 'Allia Ltd', 'Rf10, Future Business Cent, Kings Hedges Road , Cambridge, CB4 2HY', '5500', 'CO', '', '936.13', '0', 'VOID', '       ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
3 Error - no uprn e.g. ['Cambridge City Council', 'http://opendatacommunities.org/id/district-council/cambridge', '1/10/2016', '0', '00004870000117', '06/09/2016', 'Allia Ltd', 'Rf17 Future, Business Centre, Kings Hedges Road, Cambridge, CB4 2HY', '6700', 'CO', '', '1058.27', '0', 'VOID', '       ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
9 processed with voa data e.g. ['Cambridge City Council', 'http://opendatacommunities.org/id/district-council/cambridge', '1/10/2016', '200004165968', '00007350012001', '01/08/2016', 'Brimadell Property Dev Ltd', '12/13, Regent Terrace, Cambridge, CB2 1AA', '32500', 'EP', '', '6682.27', '31000', 'VOID', '       ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
Count: 4,039 Rate: 1,199,000/hour
```
It's concerning that 19 rows are rejected because the uprn isn't found in LR data.

**Comment by andreagrandi** [comment]
@davidread have you checked if it depends on a missing `0` or more at the beginning of the UPRN number?

**Comment by davidread** [comment]
good idea, will do

**Pull request merged**
